<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GameflashType', 'doctrine');

/**
 * BaseGameflashType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $GameflashType
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method Doctrine_Collection getGameflashType() Returns the current record's "GameflashType" collection
 * @method GameflashType       setName()          Sets the current record's "name" value
 * @method GameflashType       setGameflashType() Sets the current record's "GameflashType" collection
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGameflashType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gameflash_type');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Gameflash as GameflashType', array(
             'local' => 'id',
             'foreign' => 'category'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($sluggable0);
    }
}