<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Category', 'doctrine');

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $menu_text
 * @property integer $parentid
 * @property string $url
 * @property string $description
 * @property integer $status
 * @property timestamp $createdate
 * @property timestamp $modifydate
 * @property string $by
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method string    getTitle()       Returns the current record's "title" value
 * @method string    getMenuText()    Returns the current record's "menu_text" value
 * @method integer   getParentid()    Returns the current record's "parentid" value
 * @method string    getUrl()         Returns the current record's "url" value
 * @method string    getDescription() Returns the current record's "description" value
 * @method integer   getStatus()      Returns the current record's "status" value
 * @method timestamp getCreatedate()  Returns the current record's "createdate" value
 * @method timestamp getModifydate()  Returns the current record's "modifydate" value
 * @method string    getBy()          Returns the current record's "by" value
 * @method Category  setId()          Sets the current record's "id" value
 * @method Category  setTitle()       Sets the current record's "title" value
 * @method Category  setMenuText()    Sets the current record's "menu_text" value
 * @method Category  setParentid()    Sets the current record's "parentid" value
 * @method Category  setUrl()         Sets the current record's "url" value
 * @method Category  setDescription() Sets the current record's "description" value
 * @method Category  setStatus()      Sets the current record's "status" value
 * @method Category  setCreatedate()  Sets the current record's "createdate" value
 * @method Category  setModifydate()  Sets the current record's "modifydate" value
 * @method Category  setBy()          Sets the current record's "by" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('menu_text', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('parentid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('createdate', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('modifydate', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('by', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}