<?php

/**
 * BaseVtpAdvertiseImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $file_path
 * @property integer $advertise_id
 * @property string $extension
 * @property integer $priority
 * @property boolean $is_active
 * @property string $link
 * @property VtpAdvertise $VtpAdvertiseImage
 * @property SfGuardUser $SfGuardUser
 * 
 * @method string            getFilePath()          Returns the current record's "file_path" value
 * @method integer           getAdvertiseId()       Returns the current record's "advertise_id" value
 * @method string            getExtension()         Returns the current record's "extension" value
 * @method integer           getPriority()          Returns the current record's "priority" value
 * @method boolean           getIsActive()          Returns the current record's "is_active" value
 * @method string            getLink()              Returns the current record's "link" value
 * @method VtpAdvertise      getVtpAdvertiseImage() Returns the current record's "VtpAdvertiseImage" value
 * @method SfGuardUser       getSfGuardUser()       Returns the current record's "SfGuardUser" value
 * @method VtpAdvertiseImage setFilePath()          Sets the current record's "file_path" value
 * @method VtpAdvertiseImage setAdvertiseId()       Sets the current record's "advertise_id" value
 * @method VtpAdvertiseImage setExtension()         Sets the current record's "extension" value
 * @method VtpAdvertiseImage setPriority()          Sets the current record's "priority" value
 * @method VtpAdvertiseImage setIsActive()          Sets the current record's "is_active" value
 * @method VtpAdvertiseImage setLink()              Sets the current record's "link" value
 * @method VtpAdvertiseImage setVtpAdvertiseImage() Sets the current record's "VtpAdvertiseImage" value
 * @method VtpAdvertiseImage setSfGuardUser()       Sets the current record's "SfGuardUser" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVtpAdvertiseImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vtp_advertise_image');
        $this->hasColumn('file_path', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Đường dẫn file',
             'length' => 255,
             ));
        $this->hasColumn('advertise_id', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'banner quảng cáo',
             ));
        $this->hasColumn('extension', 'string', 200, array(
             'type' => 'string',
             'comment' => 'phần mở rộng của file',
             'length' => 200,
             ));
        $this->hasColumn('priority', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Độ ưu tiên hiển thị',
             'length' => 5,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trạng thái 0=chưa sử dụng, 1= sử dụng',
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Đường dẫn chi tiết (nếu có)',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('VtpAdvertise as VtpAdvertiseImage', array(
             'local' => 'advertise_id',
             'foreign' => 'id'));

        $this->hasOne('SfGuardUser', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}