<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VtpLink', 'doctrine');

/**
 * BaseVtpLink
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $group_id
 * @property string $link
 * @property string $file_path
 * @property integer $priority
 * @property integer $is_active
 * @property string $lang
 * @property string $slug
 * @property integer $created_by
 * @property integer $updated_by
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property integer $portal_id
 * @property SfGuardUser $SfGuardUser
 * @property SfGuardUser $SfGuardUser_2
 * 
 * @method integer     getId()            Returns the current record's "id" value
 * @method string      getName()          Returns the current record's "name" value
 * @method integer     getGroupId()       Returns the current record's "group_id" value
 * @method string      getLink()          Returns the current record's "link" value
 * @method string      getFilePath()      Returns the current record's "file_path" value
 * @method integer     getPriority()      Returns the current record's "priority" value
 * @method integer     getIsActive()      Returns the current record's "is_active" value
 * @method string      getLang()          Returns the current record's "lang" value
 * @method string      getSlug()          Returns the current record's "slug" value
 * @method integer     getCreatedBy()     Returns the current record's "created_by" value
 * @method integer     getUpdatedBy()     Returns the current record's "updated_by" value
 * @method timestamp   getCreatedAt()     Returns the current record's "created_at" value
 * @method timestamp   getUpdatedAt()     Returns the current record's "updated_at" value
 * @method integer     getPortalId()      Returns the current record's "portal_id" value
 * @method SfGuardUser getSfGuardUser()   Returns the current record's "SfGuardUser" value
 * @method SfGuardUser getSfGuardUser2()  Returns the current record's "SfGuardUser_2" value
 * @method VtpLink     setId()            Sets the current record's "id" value
 * @method VtpLink     setName()          Sets the current record's "name" value
 * @method VtpLink     setGroupId()       Sets the current record's "group_id" value
 * @method VtpLink     setLink()          Sets the current record's "link" value
 * @method VtpLink     setFilePath()      Sets the current record's "file_path" value
 * @method VtpLink     setPriority()      Sets the current record's "priority" value
 * @method VtpLink     setIsActive()      Sets the current record's "is_active" value
 * @method VtpLink     setLang()          Sets the current record's "lang" value
 * @method VtpLink     setSlug()          Sets the current record's "slug" value
 * @method VtpLink     setCreatedBy()     Sets the current record's "created_by" value
 * @method VtpLink     setUpdatedBy()     Sets the current record's "updated_by" value
 * @method VtpLink     setCreatedAt()     Sets the current record's "created_at" value
 * @method VtpLink     setUpdatedAt()     Sets the current record's "updated_at" value
 * @method VtpLink     setPortalId()      Sets the current record's "portal_id" value
 * @method VtpLink     setSfGuardUser()   Sets the current record's "SfGuardUser" value
 * @method VtpLink     setSfGuardUser2()  Sets the current record's "SfGuardUser_2" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVtpLink extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vtp_link');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('group_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('link', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('file_path', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('priority', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('lang', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_by', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('updated_by', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('portal_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SfGuardUser', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('SfGuardUser as SfGuardUser_2', array(
             'local' => 'updated_by',
             'foreign' => 'id'));
    }
}