<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OnlineLog', 'doctrine');

/**
 * BaseOnlineLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $peak
 * @property timestamp $time
 * @property string $dateup
 * 
 * @method integer   getId()     Returns the current record's "id" value
 * @method integer   getPeak()   Returns the current record's "peak" value
 * @method timestamp getTime()   Returns the current record's "time" value
 * @method string    getDateup() Returns the current record's "dateup" value
 * @method OnlineLog setId()     Sets the current record's "id" value
 * @method OnlineLog setPeak()   Sets the current record's "peak" value
 * @method OnlineLog setTime()   Sets the current record's "time" value
 * @method OnlineLog setDateup() Sets the current record's "dateup" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOnlineLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('online_log');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('peak', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('time', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('dateup', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}