<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VtWord', 'doctrine');

/**
 * BaseVtWord
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $word
 * @property integer $type
 * 
 * @method integer getId()   Returns the current record's "id" value
 * @method string  getWord() Returns the current record's "word" value
 * @method integer getType() Returns the current record's "type" value
 * @method VtWord  setId()   Sets the current record's "id" value
 * @method VtWord  setWord() Sets the current record's "word" value
 * @method VtWord  setType() Sets the current record's "type" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVtWord extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vt_word');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('word', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('type', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}