<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Openid', 'doctrine');

/**
 * BaseOpenid
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $userid
 * @property string $openid
 * @property integer $chanel
 * @property timestamp $datecreated
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method integer   getUserid()      Returns the current record's "userid" value
 * @method string    getOpenid()      Returns the current record's "openid" value
 * @method integer   getChanel()      Returns the current record's "chanel" value
 * @method timestamp getDatecreated() Returns the current record's "datecreated" value
 * @method Openid    setId()          Sets the current record's "id" value
 * @method Openid    setUserid()      Sets the current record's "userid" value
 * @method Openid    setOpenid()      Sets the current record's "openid" value
 * @method Openid    setChanel()      Sets the current record's "chanel" value
 * @method Openid    setDatecreated() Sets the current record's "datecreated" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOpenid extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('openid');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('userid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('openid', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('chanel', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('datecreated', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}