<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AnnouncementReaded', 'doctrine');

/**
 * BaseAnnouncementReaded
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property float $userid
 * @property string $readedid
 * 
 * @method integer            getId()       Returns the current record's "id" value
 * @method float              getUserid()   Returns the current record's "userid" value
 * @method string             getReadedid() Returns the current record's "readedid" value
 * @method AnnouncementReaded setId()       Sets the current record's "id" value
 * @method AnnouncementReaded setUserid()   Sets the current record's "userid" value
 * @method AnnouncementReaded setReadedid() Sets the current record's "readedid" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnnouncementReaded extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('announcement_readed');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('userid', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('readedid', 'string', 300, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 300,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}