<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GClient', 'doctrine');

/**
 * BaseGClient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $version
 * @property string $message
 * @property integer $force_update
 * 
 * @method integer getId()           Returns the current record's "id" value
 * @method string  getName()         Returns the current record's "name" value
 * @method string  getVersion()      Returns the current record's "version" value
 * @method string  getMessage()      Returns the current record's "message" value
 * @method integer getForceUpdate()  Returns the current record's "force_update" value
 * @method GClient setId()           Sets the current record's "id" value
 * @method GClient setName()         Sets the current record's "name" value
 * @method GClient setVersion()      Sets the current record's "version" value
 * @method GClient setMessage()      Sets the current record's "message" value
 * @method GClient setForceUpdate()  Sets the current record's "force_update" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGClient extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('g_client');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('name', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('version', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('message', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('force_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}