<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VtpMenu', 'doctrine');

/**
 * BaseVtpMenu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $image_path
 * @property integer $is_active
 * @property string $lang
 * @property integer $parent_id
 * @property string $slug
 * @property string $link
 * @property integer $level
 * @property integer $priority
 * @property integer $is_detail
 * @property integer $type
 * @property integer $created_by
 * @property integer $updated_by
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property integer $portal_id
 * @property SfGuardUser $SfGuardUser
 * @property Doctrine_Collection $VtpMenu
 * @property SfGuardUser $SfGuardUser_3
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getDescription()   Returns the current record's "description" value
 * @method string              getImagePath()     Returns the current record's "image_path" value
 * @method integer             getIsActive()      Returns the current record's "is_active" value
 * @method string              getLang()          Returns the current record's "lang" value
 * @method integer             getParentId()      Returns the current record's "parent_id" value
 * @method string              getSlug()          Returns the current record's "slug" value
 * @method string              getLink()          Returns the current record's "link" value
 * @method integer             getLevel()         Returns the current record's "level" value
 * @method integer             getPriority()      Returns the current record's "priority" value
 * @method integer             getIsDetail()      Returns the current record's "is_detail" value
 * @method integer             getType()          Returns the current record's "type" value
 * @method integer             getCreatedBy()     Returns the current record's "created_by" value
 * @method integer             getUpdatedBy()     Returns the current record's "updated_by" value
 * @method timestamp           getCreatedAt()     Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()     Returns the current record's "updated_at" value
 * @method integer             getPortalId()      Returns the current record's "portal_id" value
 * @method SfGuardUser         getSfGuardUser()   Returns the current record's "SfGuardUser" value
 * @method Doctrine_Collection getVtpMenu()       Returns the current record's "VtpMenu" collection
 * @method SfGuardUser         getSfGuardUser3()  Returns the current record's "SfGuardUser_3" value
 * @method VtpMenu             setId()            Sets the current record's "id" value
 * @method VtpMenu             setName()          Sets the current record's "name" value
 * @method VtpMenu             setDescription()   Sets the current record's "description" value
 * @method VtpMenu             setImagePath()     Sets the current record's "image_path" value
 * @method VtpMenu             setIsActive()      Sets the current record's "is_active" value
 * @method VtpMenu             setLang()          Sets the current record's "lang" value
 * @method VtpMenu             setParentId()      Sets the current record's "parent_id" value
 * @method VtpMenu             setSlug()          Sets the current record's "slug" value
 * @method VtpMenu             setLink()          Sets the current record's "link" value
 * @method VtpMenu             setLevel()         Sets the current record's "level" value
 * @method VtpMenu             setPriority()      Sets the current record's "priority" value
 * @method VtpMenu             setIsDetail()      Sets the current record's "is_detail" value
 * @method VtpMenu             setType()          Sets the current record's "type" value
 * @method VtpMenu             setCreatedBy()     Sets the current record's "created_by" value
 * @method VtpMenu             setUpdatedBy()     Sets the current record's "updated_by" value
 * @method VtpMenu             setCreatedAt()     Sets the current record's "created_at" value
 * @method VtpMenu             setUpdatedAt()     Sets the current record's "updated_at" value
 * @method VtpMenu             setPortalId()      Sets the current record's "portal_id" value
 * @method VtpMenu             setSfGuardUser()   Sets the current record's "SfGuardUser" value
 * @method VtpMenu             setVtpMenu()       Sets the current record's "VtpMenu" collection
 * @method VtpMenu             setSfGuardUser3()  Sets the current record's "SfGuardUser_3" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVtpMenu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vtp_menu');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('image_path', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('lang', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('parent_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('level', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('priority', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('is_detail', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('type', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_by', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('updated_by', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('portal_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SfGuardUser', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasMany('VtpMenu', array(
             'local' => 'id',
             'foreign' => 'parent_id'));

        $this->hasOne('SfGuardUser as SfGuardUser_3', array(
             'local' => 'updated_by',
             'foreign' => 'id'));
    }
}