<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Clan', 'doctrine');

/**
 * BaseClan
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $level
 * @property integer $avatarid
 * @property timestamp $createtime
 * @property string $tag
 * @property integer $ownerid
 * @property string $bio
 * @property integer $clanmoney
 * @property string $shortdesc
 * @property integer $totalmember
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method string    getName()        Returns the current record's "name" value
 * @method integer   getLevel()       Returns the current record's "level" value
 * @method integer   getAvatarid()    Returns the current record's "avatarid" value
 * @method timestamp getCreatetime()  Returns the current record's "createtime" value
 * @method string    getTag()         Returns the current record's "tag" value
 * @method integer   getOwnerid()     Returns the current record's "ownerid" value
 * @method string    getBio()         Returns the current record's "bio" value
 * @method integer   getClanmoney()   Returns the current record's "clanmoney" value
 * @method string    getShortdesc()   Returns the current record's "shortdesc" value
 * @method integer   getTotalmember() Returns the current record's "totalmember" value
 * @method Clan      setId()          Sets the current record's "id" value
 * @method Clan      setName()        Sets the current record's "name" value
 * @method Clan      setLevel()       Sets the current record's "level" value
 * @method Clan      setAvatarid()    Sets the current record's "avatarid" value
 * @method Clan      setCreatetime()  Sets the current record's "createtime" value
 * @method Clan      setTag()         Sets the current record's "tag" value
 * @method Clan      setOwnerid()     Sets the current record's "ownerid" value
 * @method Clan      setBio()         Sets the current record's "bio" value
 * @method Clan      setClanmoney()   Sets the current record's "clanmoney" value
 * @method Clan      setShortdesc()   Sets the current record's "shortdesc" value
 * @method Clan      setTotalmember() Sets the current record's "totalmember" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClan extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('clan');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('level', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('avatarid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '-1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('createtime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('tag', 'string', 5, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 5,
             ));
        $this->hasColumn('ownerid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('bio', 'string', 1000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1000,
             ));
        $this->hasColumn('clanmoney', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('shortdesc', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('totalmember', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}