<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Avatar', 'doctrine');

/**
 * BaseAvatar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $path
 * @property integer $category_id
 * @property integer $price
 * @property string $description
 * 
 * @method integer getId()          Returns the current record's "id" value
 * @method string  getName()        Returns the current record's "name" value
 * @method string  getPath()        Returns the current record's "path" value
 * @method integer getCategoryId()  Returns the current record's "category_id" value
 * @method integer getPrice()       Returns the current record's "price" value
 * @method string  getDescription() Returns the current record's "description" value
 * @method Avatar  setId()          Sets the current record's "id" value
 * @method Avatar  setName()        Sets the current record's "name" value
 * @method Avatar  setPath()        Sets the current record's "path" value
 * @method Avatar  setCategoryId()  Sets the current record's "category_id" value
 * @method Avatar  setPrice()       Sets the current record's "price" value
 * @method Avatar  setDescription() Sets the current record's "description" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAvatar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('avatar');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('path', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('price', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('description', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}