<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AGame', 'doctrine');

/**
 * BaseAGame
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $gamename
 * 
 * @method integer getId()       Returns the current record's "id" value
 * @method string  getGamename() Returns the current record's "gamename" value
 * @method AGame   setId()       Sets the current record's "id" value
 * @method AGame   setGamename() Sets the current record's "gamename" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAGame extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('a_game');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('gamename', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}