<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ChargeCards', 'doctrine');

/**
 * BaseChargeCards
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $cardid
 * @property string $cardname
 * 
 * @method integer     getId()       Returns the current record's "id" value
 * @method integer     getCardid()   Returns the current record's "cardid" value
 * @method string      getCardname() Returns the current record's "cardname" value
 * @method ChargeCards setId()       Sets the current record's "id" value
 * @method ChargeCards setCardid()   Sets the current record's "cardid" value
 * @method ChargeCards setCardname() Sets the current record's "cardname" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChargeCards extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('charge_cards');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('cardid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cardname', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}