<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PromotionRule', 'doctrine');

/**
 * BasePromotionRule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $rule_id
 * @property timestamp $rule_start
 * @property timestamp $rule_end
 * @property integer $rule_card
 * @property integer $rule_sms
 * @property integer $rule_active
 * @property string $rule_title
 * @property string $rule_description
 * @property integer $rule_card_special
 * @property integer $rule_price_tier
 * @property string $cp
 * @property integer $rule_high_card_special
 * @property integer $rule_high_price_tier
 * 
 * @method integer       getRuleId()                 Returns the current record's "rule_id" value
 * @method timestamp     getRuleStart()              Returns the current record's "rule_start" value
 * @method timestamp     getRuleEnd()                Returns the current record's "rule_end" value
 * @method integer       getRuleCard()               Returns the current record's "rule_card" value
 * @method integer       getRuleSms()                Returns the current record's "rule_sms" value
 * @method integer       getRuleActive()             Returns the current record's "rule_active" value
 * @method string        getRuleTitle()              Returns the current record's "rule_title" value
 * @method string        getRuleDescription()        Returns the current record's "rule_description" value
 * @method integer       getRuleCardSpecial()        Returns the current record's "rule_card_special" value
 * @method integer       getRulePriceTier()          Returns the current record's "rule_price_tier" value
 * @method string        getCp()                     Returns the current record's "cp" value
 * @method integer       getRuleHighCardSpecial()    Returns the current record's "rule_high_card_special" value
 * @method integer       getRuleHighPriceTier()      Returns the current record's "rule_high_price_tier" value
 * @method PromotionRule setRuleId()                 Sets the current record's "rule_id" value
 * @method PromotionRule setRuleStart()              Sets the current record's "rule_start" value
 * @method PromotionRule setRuleEnd()                Sets the current record's "rule_end" value
 * @method PromotionRule setRuleCard()               Sets the current record's "rule_card" value
 * @method PromotionRule setRuleSms()                Sets the current record's "rule_sms" value
 * @method PromotionRule setRuleActive()             Sets the current record's "rule_active" value
 * @method PromotionRule setRuleTitle()              Sets the current record's "rule_title" value
 * @method PromotionRule setRuleDescription()        Sets the current record's "rule_description" value
 * @method PromotionRule setRuleCardSpecial()        Sets the current record's "rule_card_special" value
 * @method PromotionRule setRulePriceTier()          Sets the current record's "rule_price_tier" value
 * @method PromotionRule setCp()                     Sets the current record's "cp" value
 * @method PromotionRule setRuleHighCardSpecial()    Sets the current record's "rule_high_card_special" value
 * @method PromotionRule setRuleHighPriceTier()      Sets the current record's "rule_high_price_tier" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePromotionRule extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('promotion_rule');
        $this->hasColumn('rule_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('rule_start', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('rule_end', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('rule_card', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('rule_sms', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('rule_active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('rule_title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('rule_description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('rule_card_special', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('rule_price_tier', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '5000000',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cp', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('rule_high_card_special', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('rule_high_price_tier', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '500000',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}