<?php

/**
 * BaseVtChargAmount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property double $charg_amount
 * @property string $description
 * @property Doctrine_Collection $VtSerialCode
 * 
 * @method double              getChargAmount()  Returns the current record's "charg_amount" value
 * @method string              getDescription()  Returns the current record's "description" value
 * @method Doctrine_Collection getVtSerialCode() Returns the current record's "VtSerialCode" collection
 * @method VtChargAmount       setChargAmount()  Sets the current record's "charg_amount" value
 * @method VtChargAmount       setDescription()  Sets the current record's "description" value
 * @method VtChargAmount       setVtSerialCode() Sets the current record's "VtSerialCode" collection
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVtChargAmount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vt_charg_amount');
        $this->hasColumn('charg_amount', 'double', null, array(
             'type' => 'double',
             'unique' => true,
             'notnull' => true,
             'comment' => 'Tỉ lệ chia sẻ doanh thu đối với từng Loại nhà phát triển',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => '',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('VtSerialCode', array(
             'local' => 'id',
             'foreign' => 'charg_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}