<?php

/**
 * BaseVtDaiLy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $code
 * @property Doctrine_Collection $VtSerialCode
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getCode()         Returns the current record's "code" value
 * @method Doctrine_Collection getVtSerialCode() Returns the current record's "VtSerialCode" collection
 * @method VtDaiLy             setName()         Sets the current record's "name" value
 * @method VtDaiLy             setCode()         Sets the current record's "code" value
 * @method VtDaiLy             setVtSerialCode() Sets the current record's "VtSerialCode" collection
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVtDaiLy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vt_dai_ly');
        $this->hasColumn('name', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'comment' => 'Ten dai ly',
             'length' => 30,
             ));
        $this->hasColumn('code', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'comment' => 'Ma dai ly',
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('VtSerialCode', array(
             'local' => 'id',
             'foreign' => 'dai_ly_id'));
    }
}