<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Clanupgrade', 'doctrine');

/**
 * BaseClanupgrade
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $level
 * @property integer $money
 * @property integer $totalslot
 * 
 * @method integer     getId()        Returns the current record's "id" value
 * @method integer     getLevel()     Returns the current record's "level" value
 * @method integer     getMoney()     Returns the current record's "money" value
 * @method integer     getTotalslot() Returns the current record's "totalslot" value
 * @method Clanupgrade setId()        Sets the current record's "id" value
 * @method Clanupgrade setLevel()     Sets the current record's "level" value
 * @method Clanupgrade setMoney()     Sets the current record's "money" value
 * @method Clanupgrade setTotalslot() Sets the current record's "totalslot" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClanupgrade extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('clanupgrade');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('level', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('money', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '50000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('totalslot', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}