<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LogSms', 'doctrine');

/**
 * BaseLogSms
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $sender
 * @property string $recipient
 * @property string $mobody
 * @property string $mtbody
 * @property string $cpid
 * @property integer $status
 * @property timestamp $datecreated
 * @property string $sendnumber
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method string    getSender()      Returns the current record's "sender" value
 * @method string    getRecipient()   Returns the current record's "recipient" value
 * @method string    getMobody()      Returns the current record's "mobody" value
 * @method string    getMtbody()      Returns the current record's "mtbody" value
 * @method string    getCpid()        Returns the current record's "cpid" value
 * @method integer   getStatus()      Returns the current record's "status" value
 * @method timestamp getDatecreated() Returns the current record's "datecreated" value
 * @method string    getSendnumber()  Returns the current record's "sendnumber" value
 * @method LogSms    setId()          Sets the current record's "id" value
 * @method LogSms    setSender()      Sets the current record's "sender" value
 * @method LogSms    setRecipient()   Sets the current record's "recipient" value
 * @method LogSms    setMobody()      Sets the current record's "mobody" value
 * @method LogSms    setMtbody()      Sets the current record's "mtbody" value
 * @method LogSms    setCpid()        Sets the current record's "cpid" value
 * @method LogSms    setStatus()      Sets the current record's "status" value
 * @method LogSms    setDatecreated() Sets the current record's "datecreated" value
 * @method LogSms    setSendnumber()  Sets the current record's "sendnumber" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLogSms extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('log_sms');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('sender', 'string', 12, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 12,
             ));
        $this->hasColumn('recipient', 'string', 12, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 12,
             ));
        $this->hasColumn('mobody', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('mtbody', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('cpid', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('datecreated', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('sendnumber', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}