<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Messagetype', 'doctrine');

/**
 * BaseMessagetype
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $type
 * 
 * @method integer     getId()   Returns the current record's "id" value
 * @method string      getType() Returns the current record's "type" value
 * @method Messagetype setId()   Sets the current record's "id" value
 * @method Messagetype setType() Sets the current record's "type" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMessagetype extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('messagetype');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('type', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}