<?php

/**
 * BaseLevel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property bigint $cash
 * @property string $description
 * @property int $level
 * @property string $exp
 * @property int $cashGift
 * @property Doctrine_Collection $GUser
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method bigint              getCash()        Returns the current record's "cash" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method int                 getLevel()       Returns the current record's "level" value
 * @method string              getExp()         Returns the current record's "exp" value
 * @method int                 getCashGift()    Returns the current record's "cashGift" value
 * @method Doctrine_Collection getGUser()       Returns the current record's "GUser" collection
 * @method Level               setName()        Sets the current record's "name" value
 * @method Level               setCash()        Sets the current record's "cash" value
 * @method Level               setDescription() Sets the current record's "description" value
 * @method Level               setLevel()       Sets the current record's "level" value
 * @method Level               setExp()         Sets the current record's "exp" value
 * @method Level               setCashGift()    Sets the current record's "cashGift" value
 * @method Level               setGUser()       Sets the current record's "GUser" collection
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLevel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('level');
        $this->hasColumn('name', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'comment' => 'Ten level',
             'length' => 20,
             ));
        $this->hasColumn('cash', 'bigint', 30, array(
             'type' => 'bigint',
             'notnull' => true,
             'unique' => true,
             'comment' => 'Số tiền đạt cấp',
             'length' => 30,
             ));
        $this->hasColumn('description', 'string', 300, array(
             'type' => 'string',
             'comment' => 'Mô tả',
             'length' => 300,
             ));
        $this->hasColumn('level', 'int', 11, array(
             'type' => 'int',
             'notnull' => true,
             'unique' => true,
             'comment' => 'level',
             'length' => 11,
             ));
        $this->hasColumn('exp', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'comment' => 'kinh nghiệm',
             'length' => 30,
             ));
        $this->hasColumn('cashGift', 'int', 11, array(
             'type' => 'int',
             'notnull' => true,
             'unique' => true,
             'comment' => 'quà tặng',
             'length' => 11,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('GUser', array(
             'local' => 'id',
             'foreign' => 'level_id'));
    }
}