<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VtpCategory', 'doctrine');

/**
 * BaseVtpCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $image_path
 * @property integer $is_active
 * @property string $lang
 * @property integer $parent_id
 * @property string $slug
 * @property string $link
 * @property integer $level
 * @property integer $priority
 * @property string $type
 * @property integer $is_detail
 * @property integer $created_by
 * @property integer $updated_by
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property integer $portal_id
 * @property SfGuardUser $SfGuardUser
 * @property Doctrine_Collection $VtpCategory
 * @property SfGuardUser $SfGuardUser_3
 * @property Doctrine_Collection $VtpArticle
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getDescription()   Returns the current record's "description" value
 * @method string              getImagePath()     Returns the current record's "image_path" value
 * @method integer             getIsActive()      Returns the current record's "is_active" value
 * @method string              getLang()          Returns the current record's "lang" value
 * @method integer             getParentId()      Returns the current record's "parent_id" value
 * @method string              getSlug()          Returns the current record's "slug" value
 * @method string              getLink()          Returns the current record's "link" value
 * @method integer             getLevel()         Returns the current record's "level" value
 * @method integer             getPriority()      Returns the current record's "priority" value
 * @method string              getType()          Returns the current record's "type" value
 * @method integer             getIsDetail()      Returns the current record's "is_detail" value
 * @method integer             getCreatedBy()     Returns the current record's "created_by" value
 * @method integer             getUpdatedBy()     Returns the current record's "updated_by" value
 * @method timestamp           getCreatedAt()     Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()     Returns the current record's "updated_at" value
 * @method integer             getPortalId()      Returns the current record's "portal_id" value
 * @method SfGuardUser         getSfGuardUser()   Returns the current record's "SfGuardUser" value
 * @method Doctrine_Collection getVtpCategory()   Returns the current record's "VtpCategory" collection
 * @method SfGuardUser         getSfGuardUser3()  Returns the current record's "SfGuardUser_3" value
 * @method Doctrine_Collection getVtpArticle()    Returns the current record's "VtpArticle" collection
 * @method VtpCategory         setId()            Sets the current record's "id" value
 * @method VtpCategory         setName()          Sets the current record's "name" value
 * @method VtpCategory         setDescription()   Sets the current record's "description" value
 * @method VtpCategory         setImagePath()     Sets the current record's "image_path" value
 * @method VtpCategory         setIsActive()      Sets the current record's "is_active" value
 * @method VtpCategory         setLang()          Sets the current record's "lang" value
 * @method VtpCategory         setParentId()      Sets the current record's "parent_id" value
 * @method VtpCategory         setSlug()          Sets the current record's "slug" value
 * @method VtpCategory         setLink()          Sets the current record's "link" value
 * @method VtpCategory         setLevel()         Sets the current record's "level" value
 * @method VtpCategory         setPriority()      Sets the current record's "priority" value
 * @method VtpCategory         setType()          Sets the current record's "type" value
 * @method VtpCategory         setIsDetail()      Sets the current record's "is_detail" value
 * @method VtpCategory         setCreatedBy()     Sets the current record's "created_by" value
 * @method VtpCategory         setUpdatedBy()     Sets the current record's "updated_by" value
 * @method VtpCategory         setCreatedAt()     Sets the current record's "created_at" value
 * @method VtpCategory         setUpdatedAt()     Sets the current record's "updated_at" value
 * @method VtpCategory         setPortalId()      Sets the current record's "portal_id" value
 * @method VtpCategory         setSfGuardUser()   Sets the current record's "SfGuardUser" value
 * @method VtpCategory         setVtpCategory()   Sets the current record's "VtpCategory" collection
 * @method VtpCategory         setSfGuardUser3()  Sets the current record's "SfGuardUser_3" value
 * @method VtpCategory         setVtpArticle()    Sets the current record's "VtpArticle" collection
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVtpCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vtp_category');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('image_path', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('lang', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('parent_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('level', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('priority', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('type', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('is_detail', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('created_by', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('updated_by', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('portal_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SfGuardUser', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasMany('VtpCategory', array(
             'local' => 'id',
             'foreign' => 'parent_id'));

        $this->hasOne('SfGuardUser as SfGuardUser_3', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $this->hasMany('VtpArticle', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}