<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DeviceInfo', 'doctrine');

/**
 * BaseDeviceInfo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $unique_id
 * @property string $device_series
 * @property string $os
 * @property integer $cp_id
 * @property timestamp $time
 * 
 * @method integer    getId()            Returns the current record's "id" value
 * @method string     getUniqueId()      Returns the current record's "unique_id" value
 * @method string     getDeviceSeries()  Returns the current record's "device_series" value
 * @method string     getOs()            Returns the current record's "os" value
 * @method integer    getCpId()          Returns the current record's "cp_id" value
 * @method timestamp  getTime()          Returns the current record's "time" value
 * @method DeviceInfo setId()            Sets the current record's "id" value
 * @method DeviceInfo setUniqueId()      Sets the current record's "unique_id" value
 * @method DeviceInfo setDeviceSeries()  Sets the current record's "device_series" value
 * @method DeviceInfo setOs()            Sets the current record's "os" value
 * @method DeviceInfo setCpId()          Sets the current record's "cp_id" value
 * @method DeviceInfo setTime()          Sets the current record's "time" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDeviceInfo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('device_info');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('unique_id', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('device_series', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('os', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('cp_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('time', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}