<?php

/**
 * BaseVtpAdvertiseLocation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $page
 * @property string $template
 * @property integer $advertise_id
 * @property integer $priority
 * @property integer $portal_id
 * @property Doctrine_Collection $VtpAdvertiseLocation
 * 
 * @method string               getName()                 Returns the current record's "name" value
 * @method string               getPage()                 Returns the current record's "page" value
 * @method string               getTemplate()             Returns the current record's "template" value
 * @method integer              getAdvertiseId()          Returns the current record's "advertise_id" value
 * @method integer              getPriority()             Returns the current record's "priority" value
 * @method integer              getPortalId()             Returns the current record's "portal_id" value
 * @method Doctrine_Collection  getVtpAdvertiseLocation() Returns the current record's "VtpAdvertiseLocation" collection
 * @method VtpAdvertiseLocation setName()                 Sets the current record's "name" value
 * @method VtpAdvertiseLocation setPage()                 Sets the current record's "page" value
 * @method VtpAdvertiseLocation setTemplate()             Sets the current record's "template" value
 * @method VtpAdvertiseLocation setAdvertiseId()          Sets the current record's "advertise_id" value
 * @method VtpAdvertiseLocation setPriority()             Sets the current record's "priority" value
 * @method VtpAdvertiseLocation setPortalId()             Sets the current record's "portal_id" value
 * @method VtpAdvertiseLocation setVtpAdvertiseLocation() Sets the current record's "VtpAdvertiseLocation" collection
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVtpAdvertiseLocation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vtp_advertise_location');
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Ten vi tri quang cao',
             'length' => 200,
             ));
        $this->hasColumn('page', 'string', 200, array(
             'type' => 'string',
             'comment' => 'Trang hiển thị',
             'length' => 200,
             ));
        $this->hasColumn('template', 'string', 200, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'Duong dan toi file template quang cao',
             'length' => 200,
             ));
        $this->hasColumn('advertise_id', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'banner quảng cáo',
             ));
        $this->hasColumn('priority', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Thứ tự hiển thị',
             'length' => 5,
             ));
        $this->hasColumn('portal_id', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'Portal cần hiển thị nội dung, được quy ước trong file cấu hình (Khách hàng cá nhân / Khách hàng doanh nghiệp)',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('VtpAdvertise as VtpAdvertiseLocation', array(
             'local' => 'advertise_id',
             'foreign' => 'id'));
    }
}