<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SfGuardUser', 'doctrine');

/**
 * BaseSfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $first_name
 * @property string $last_name
 * @property string $phone
 * @property string $email_address
 * @property string $username
 * @property integer $cp
 * @property string $algorithm
 * @property string $salt
 * @property string $password
 * @property integer $is_active
 * @property integer $is_super_admin
 * @property timestamp $last_login
 * @property timestamp $pass_update_at
 * @property integer $is_lock_signin
 * @property integer $locked_time
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $SfGuardForgotPassword
 * @property Doctrine_Collection $SfGuardRememberKey
 * @property Doctrine_Collection $SfGuardUserGroup
 * @property Doctrine_Collection $SfGuardUserPermission
 * @property Doctrine_Collection $VtpAdvertise
 * @property Doctrine_Collection $VtpAdvertise_2
 * @property Doctrine_Collection $VtpAdvertiseImage
 * @property Doctrine_Collection $VtpAdvertiseImage_3
 * @property Doctrine_Collection $VtpArticle
 * @property Doctrine_Collection $VtpArticle_3
 * @property Doctrine_Collection $VtpCategory
 * @property Doctrine_Collection $VtpCategory_3
 * @property Doctrine_Collection $VtpHtml
 * @property Doctrine_Collection $VtpHtml_2
 * @property Doctrine_Collection $VtpLink
 * @property Doctrine_Collection $VtpLink_2
 * @property Doctrine_Collection $VtpMenu
 * @property Doctrine_Collection $VtpMenu_3
 * @property Doctrine_Collection $VtSerialCode
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getFirstName()             Returns the current record's "first_name" value
 * @method string              getLastName()              Returns the current record's "last_name" value
 * @method string              getPhone()                 Returns the current record's "phone" value
 * @method string              getEmailAddress()          Returns the current record's "email_address" value
 * @method string              getUsername()              Returns the current record's "username" value
 * @method integer             getCp()                    Returns the current record's "cp" value
 * @method string              getAlgorithm()             Returns the current record's "algorithm" value
 * @method string              getSalt()                  Returns the current record's "salt" value
 * @method string              getPassword()              Returns the current record's "password" value
 * @method integer             getIsActive()              Returns the current record's "is_active" value
 * @method integer             getIsSuperAdmin()          Returns the current record's "is_super_admin" value
 * @method timestamp           getLastLogin()             Returns the current record's "last_login" value
 * @method timestamp           getPassUpdateAt()          Returns the current record's "pass_update_at" value
 * @method integer             getIsLockSignin()          Returns the current record's "is_lock_signin" value
 * @method integer             getLockedTime()            Returns the current record's "locked_time" value
 * @method timestamp           getCreatedAt()             Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()             Returns the current record's "updated_at" value
 * @method Doctrine_Collection getSfGuardForgotPassword() Returns the current record's "SfGuardForgotPassword" collection
 * @method Doctrine_Collection getSfGuardRememberKey()    Returns the current record's "SfGuardRememberKey" collection
 * @method Doctrine_Collection getSfGuardUserGroup()      Returns the current record's "SfGuardUserGroup" collection
 * @method Doctrine_Collection getSfGuardUserPermission() Returns the current record's "SfGuardUserPermission" collection
 * @method Doctrine_Collection getVtpAdvertise()          Returns the current record's "VtpAdvertise" collection
 * @method Doctrine_Collection getVtpAdvertise2()         Returns the current record's "VtpAdvertise_2" collection
 * @method Doctrine_Collection getVtpAdvertiseImage()     Returns the current record's "VtpAdvertiseImage" collection
 * @method Doctrine_Collection getVtpAdvertiseImage3()    Returns the current record's "VtpAdvertiseImage_3" collection
 * @method Doctrine_Collection getVtpArticle()            Returns the current record's "VtpArticle" collection
 * @method Doctrine_Collection getVtpArticle3()           Returns the current record's "VtpArticle_3" collection
 * @method Doctrine_Collection getVtpCategory()           Returns the current record's "VtpCategory" collection
 * @method Doctrine_Collection getVtpCategory3()          Returns the current record's "VtpCategory_3" collection
 * @method Doctrine_Collection getVtpHtml()               Returns the current record's "VtpHtml" collection
 * @method Doctrine_Collection getVtpHtml2()              Returns the current record's "VtpHtml_2" collection
 * @method Doctrine_Collection getVtpLink()               Returns the current record's "VtpLink" collection
 * @method Doctrine_Collection getVtpLink2()              Returns the current record's "VtpLink_2" collection
 * @method Doctrine_Collection getVtpMenu()               Returns the current record's "VtpMenu" collection
 * @method Doctrine_Collection getVtpMenu3()              Returns the current record's "VtpMenu_3" collection
 * @method Doctrine_Collection getVtSerialCode()          Returns the current record's "VtSerialCode" collection
 * @method SfGuardUser         setId()                    Sets the current record's "id" value
 * @method SfGuardUser         setFirstName()             Sets the current record's "first_name" value
 * @method SfGuardUser         setLastName()              Sets the current record's "last_name" value
 * @method SfGuardUser         setPhone()                 Sets the current record's "phone" value
 * @method SfGuardUser         setEmailAddress()          Sets the current record's "email_address" value
 * @method SfGuardUser         setUsername()              Sets the current record's "username" value
 * @method SfGuardUser         setCp()                    Sets the current record's "cp" value
 * @method SfGuardUser         setAlgorithm()             Sets the current record's "algorithm" value
 * @method SfGuardUser         setSalt()                  Sets the current record's "salt" value
 * @method SfGuardUser         setPassword()              Sets the current record's "password" value
 * @method SfGuardUser         setIsActive()              Sets the current record's "is_active" value
 * @method SfGuardUser         setIsSuperAdmin()          Sets the current record's "is_super_admin" value
 * @method SfGuardUser         setLastLogin()             Sets the current record's "last_login" value
 * @method SfGuardUser         setPassUpdateAt()          Sets the current record's "pass_update_at" value
 * @method SfGuardUser         setIsLockSignin()          Sets the current record's "is_lock_signin" value
 * @method SfGuardUser         setLockedTime()            Sets the current record's "locked_time" value
 * @method SfGuardUser         setCreatedAt()             Sets the current record's "created_at" value
 * @method SfGuardUser         setUpdatedAt()             Sets the current record's "updated_at" value
 * @method SfGuardUser         setSfGuardForgotPassword() Sets the current record's "SfGuardForgotPassword" collection
 * @method SfGuardUser         setSfGuardRememberKey()    Sets the current record's "SfGuardRememberKey" collection
 * @method SfGuardUser         setSfGuardUserGroup()      Sets the current record's "SfGuardUserGroup" collection
 * @method SfGuardUser         setSfGuardUserPermission() Sets the current record's "SfGuardUserPermission" collection
 * @method SfGuardUser         setVtpAdvertise()          Sets the current record's "VtpAdvertise" collection
 * @method SfGuardUser         setVtpAdvertise2()         Sets the current record's "VtpAdvertise_2" collection
 * @method SfGuardUser         setVtpAdvertiseImage()     Sets the current record's "VtpAdvertiseImage" collection
 * @method SfGuardUser         setVtpAdvertiseImage3()    Sets the current record's "VtpAdvertiseImage_3" collection
 * @method SfGuardUser         setVtpArticle()            Sets the current record's "VtpArticle" collection
 * @method SfGuardUser         setVtpArticle3()           Sets the current record's "VtpArticle_3" collection
 * @method SfGuardUser         setVtpCategory()           Sets the current record's "VtpCategory" collection
 * @method SfGuardUser         setVtpCategory3()          Sets the current record's "VtpCategory_3" collection
 * @method SfGuardUser         setVtpHtml()               Sets the current record's "VtpHtml" collection
 * @method SfGuardUser         setVtpHtml2()              Sets the current record's "VtpHtml_2" collection
 * @method SfGuardUser         setVtpLink()               Sets the current record's "VtpLink" collection
 * @method SfGuardUser         setVtpLink2()              Sets the current record's "VtpLink_2" collection
 * @method SfGuardUser         setVtpMenu()               Sets the current record's "VtpMenu" collection
 * @method SfGuardUser         setVtpMenu3()              Sets the current record's "VtpMenu_3" collection
 * @method SfGuardUser         setVtSerialCode()          Sets the current record's "VtSerialCode" collection
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSfGuardUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('email_address', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('username', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('cp', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('algorithm', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'sha1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('salt', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('is_super_admin', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('last_login', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('pass_update_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('is_lock_signin', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('locked_time', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SfGuardForgotPassword', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('SfGuardRememberKey', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('SfGuardUserGroup', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('SfGuardUserPermission', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('VtpAdvertise', array(
             'local' => 'id',
             'foreign' => 'created_by'));

        $this->hasMany('VtpAdvertise as VtpAdvertise_2', array(
             'local' => 'id',
             'foreign' => 'updated_by'));

        $this->hasMany('VtpAdvertiseImage', array(
             'local' => 'id',
             'foreign' => 'created_by'));

        $this->hasMany('VtpAdvertiseImage as VtpAdvertiseImage_3', array(
             'local' => 'id',
             'foreign' => 'updated_by'));

        $this->hasMany('VtpArticle', array(
             'local' => 'id',
             'foreign' => 'created_by'));

        $this->hasMany('VtpArticle as VtpArticle_3', array(
             'local' => 'id',
             'foreign' => 'updated_by'));

        $this->hasMany('VtpCategory', array(
             'local' => 'id',
             'foreign' => 'created_by'));

        $this->hasMany('VtpCategory as VtpCategory_3', array(
             'local' => 'id',
             'foreign' => 'updated_by'));

        $this->hasMany('VtpHtml', array(
             'local' => 'id',
             'foreign' => 'created_by'));

        $this->hasMany('VtpHtml as VtpHtml_2', array(
             'local' => 'id',
             'foreign' => 'updated_by'));

        $this->hasMany('VtpLink', array(
             'local' => 'id',
             'foreign' => 'created_by'));

        $this->hasMany('VtpLink as VtpLink_2', array(
             'local' => 'id',
             'foreign' => 'updated_by'));

        $this->hasMany('VtpMenu', array(
             'local' => 'id',
             'foreign' => 'created_by'));

        $this->hasMany('VtpMenu as VtpMenu_3', array(
             'local' => 'id',
             'foreign' => 'updated_by'));

        $this->hasMany('VtSerialCode', array(
             'local' => 'id',
             'foreign' => 'admin_id'));
    }
}