<?php

/**
 * BaseVtSerialCode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $serial
 * @property string $cardnumber
 * @property double $user_id
 * @property double $charg_id
 * @property string $type
 * @property boolean $is_status
 * @property datetime $end_date
 * @property bigint $dai_ly_id
 * @property bigint $admin_id
 * @property VtChargAmount $VtChargAmount
 * @property VtDaiLy $VtDaiLy
 * @property SfGuardUser $SfGuardUser
 * 
 * @method string        getSerial()        Returns the current record's "serial" value
 * @method string        getCardnumber()    Returns the current record's "cardnumber" value
 * @method double        getUserId()        Returns the current record's "user_id" value
 * @method double        getChargId()       Returns the current record's "charg_id" value
 * @method string        getType()          Returns the current record's "type" value
 * @method boolean       getIsStatus()      Returns the current record's "is_status" value
 * @method datetime      getEndDate()       Returns the current record's "end_date" value
 * @method bigint        getDaiLyId()       Returns the current record's "dai_ly_id" value
 * @method bigint        getAdminId()       Returns the current record's "admin_id" value
 * @method VtChargAmount getVtChargAmount() Returns the current record's "VtChargAmount" value
 * @method VtDaiLy       getVtDaiLy()       Returns the current record's "VtDaiLy" value
 * @method SfGuardUser   getSfGuardUser()   Returns the current record's "SfGuardUser" value
 * @method VtSerialCode  setSerial()        Sets the current record's "serial" value
 * @method VtSerialCode  setCardnumber()    Sets the current record's "cardnumber" value
 * @method VtSerialCode  setUserId()        Sets the current record's "user_id" value
 * @method VtSerialCode  setChargId()       Sets the current record's "charg_id" value
 * @method VtSerialCode  setType()          Sets the current record's "type" value
 * @method VtSerialCode  setIsStatus()      Sets the current record's "is_status" value
 * @method VtSerialCode  setEndDate()       Sets the current record's "end_date" value
 * @method VtSerialCode  setDaiLyId()       Sets the current record's "dai_ly_id" value
 * @method VtSerialCode  setAdminId()       Sets the current record's "admin_id" value
 * @method VtSerialCode  setVtChargAmount() Sets the current record's "VtChargAmount" value
 * @method VtSerialCode  setVtDaiLy()       Sets the current record's "VtDaiLy" value
 * @method VtSerialCode  setSfGuardUser()   Sets the current record's "SfGuardUser" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVtSerialCode extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vt_serial_code');
        $this->hasColumn('serial', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => '',
             'length' => 30,
             ));
        $this->hasColumn('cardnumber', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => '',
             'length' => 30,
             ));
        $this->hasColumn('user_id', 'double', null, array(
             'type' => 'double',
             'notnull' => true,
             'comment' => 'id người nạp',
             ));
        $this->hasColumn('charg_id', 'double', null, array(
             'type' => 'double',
             'notnull' => true,
             'comment' => 'Loại mệnh giá',
             ));
        $this->hasColumn('type', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'VG',
             'comment' => 'Loại thẻ nạp, tạo ra mặc định là VG',
             'length' => 10,
             ));
        $this->hasColumn('is_status', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             'comment' => 'Trạng thái của thẻ',
             ));
        $this->hasColumn('end_date', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             'comment' => 'Thời hạn của thẻ nạp',
             ));
        $this->hasColumn('dai_ly_id', 'bigint', null, array(
             'type' => 'bigint',
             'notnull' => true,
             'comment' => 'Id đại lý nhận được thẻ',
             ));
        $this->hasColumn('admin_id', 'bigint', null, array(
             'type' => 'bigint',
             'notnull' => true,
             'comment' => 'Id admin tạo thẻ nạp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('VtChargAmount', array(
             'local' => 'charg_id',
             'foreign' => 'id'));

        $this->hasOne('VtDaiLy', array(
             'local' => 'dai_ly_id',
             'foreign' => 'id'));

        $this->hasOne('SfGuardUser', array(
             'local' => 'admin_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}