<?php

/**
 * BaseVtpAdvertise
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property string $location
 * @property string $view_type
 * @property integer $amount
 * @property integer $width
 * @property integer $height
 * @property boolean $is_active
 * @property integer $portal_id
 * @property SfGuardUser $SfGuardUser
 * @property Doctrine_Collection $AdvertiseImage
 * @property VtpAdvertiseLocation $AdvertiseLocation
 * 
 * @method string               getName()              Returns the current record's "name" value
 * @method string               getDescription()       Returns the current record's "description" value
 * @method string               getLocation()          Returns the current record's "location" value
 * @method string               getViewType()          Returns the current record's "view_type" value
 * @method integer              getAmount()            Returns the current record's "amount" value
 * @method integer              getWidth()             Returns the current record's "width" value
 * @method integer              getHeight()            Returns the current record's "height" value
 * @method boolean              getIsActive()          Returns the current record's "is_active" value
 * @method integer              getPortalId()          Returns the current record's "portal_id" value
 * @method SfGuardUser          getSfGuardUser()       Returns the current record's "SfGuardUser" value
 * @method Doctrine_Collection  getAdvertiseImage()    Returns the current record's "AdvertiseImage" collection
 * @method VtpAdvertiseLocation getAdvertiseLocation() Returns the current record's "AdvertiseLocation" value
 * @method VtpAdvertise         setName()              Sets the current record's "name" value
 * @method VtpAdvertise         setDescription()       Sets the current record's "description" value
 * @method VtpAdvertise         setLocation()          Sets the current record's "location" value
 * @method VtpAdvertise         setViewType()          Sets the current record's "view_type" value
 * @method VtpAdvertise         setAmount()            Sets the current record's "amount" value
 * @method VtpAdvertise         setWidth()             Sets the current record's "width" value
 * @method VtpAdvertise         setHeight()            Sets the current record's "height" value
 * @method VtpAdvertise         setIsActive()          Sets the current record's "is_active" value
 * @method VtpAdvertise         setPortalId()          Sets the current record's "portal_id" value
 * @method VtpAdvertise         setSfGuardUser()       Sets the current record's "SfGuardUser" value
 * @method VtpAdvertise         setAdvertiseImage()    Sets the current record's "AdvertiseImage" collection
 * @method VtpAdvertise         setAdvertiseLocation() Sets the current record's "AdvertiseLocation" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVtpAdvertise extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vtp_advertise');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Tên banner',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'comment' => 'Mô tả',
             'length' => 500,
             ));
        $this->hasColumn('location', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Trang hiển thị',
             'length' => 255,
             ));
        $this->hasColumn('view_type', 'string', 10, array(
             'type' => 'string',
             'comment' => 'Kiểu hiển thị S=Slide, F=Flash, I=Ảnh',
             'length' => 10,
             ));
        $this->hasColumn('amount', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'Số lượng ảnh hiển thị',
             'default' => 0,
             ));
        $this->hasColumn('width', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'Chiều rộng',
             'default' => 0,
             ));
        $this->hasColumn('height', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'Chiều cao',
             'default' => 0,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trạng thái 0=chưa sử dụng, 1= sử dụng',
             ));
        $this->hasColumn('portal_id', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'Portal cần hiển thị nội dung, được quy ước trong file cấu hình (Khách hàng cá nhân / Khách hàng doanh nghiệp)',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SfGuardUser', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasMany('VtpAdvertiseImage as AdvertiseImage', array(
             'local' => 'id',
             'foreign' => 'advertise_id'));

        $this->hasOne('VtpAdvertiseLocation as AdvertiseLocation', array(
             'local' => 'id',
             'foreign' => 'advertise_id'));

        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}