<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SmsLog', 'doctrine');

/**
 * BaseSmsLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $send_number
 * @property string $shortcode
 * @property string $mobody
 * @property string $mtbody
 * @property string $cp_id
 * @property integer $status
 * @property timestamp $datecreated
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method string    getSendNumber()  Returns the current record's "send_number" value
 * @method string    getShortcode()   Returns the current record's "shortcode" value
 * @method string    getMobody()      Returns the current record's "mobody" value
 * @method string    getMtbody()      Returns the current record's "mtbody" value
 * @method string    getCpId()        Returns the current record's "cp_id" value
 * @method integer   getStatus()      Returns the current record's "status" value
 * @method timestamp getDatecreated() Returns the current record's "datecreated" value
 * @method SmsLog    setId()          Sets the current record's "id" value
 * @method SmsLog    setSendNumber()  Sets the current record's "send_number" value
 * @method SmsLog    setShortcode()   Sets the current record's "shortcode" value
 * @method SmsLog    setMobody()      Sets the current record's "mobody" value
 * @method SmsLog    setMtbody()      Sets the current record's "mtbody" value
 * @method SmsLog    setCpId()        Sets the current record's "cp_id" value
 * @method SmsLog    setStatus()      Sets the current record's "status" value
 * @method SmsLog    setDatecreated() Sets the current record's "datecreated" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSmsLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sms_log');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('send_number', 'string', 12, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 12,
             ));
        $this->hasColumn('shortcode', 'string', 12, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 12,
             ));
        $this->hasColumn('mobody', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('mtbody', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('cp_id', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('datecreated', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}