<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SmsValue', 'doctrine');

/**
 * BaseSmsValue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $code
 * @property integer $vm_money
 * 
 * @method integer  getId()       Returns the current record's "id" value
 * @method integer  getCode()     Returns the current record's "code" value
 * @method integer  getVmMoney()  Returns the current record's "vm_money" value
 * @method SmsValue setId()       Sets the current record's "id" value
 * @method SmsValue setCode()     Sets the current record's "code" value
 * @method SmsValue setVmMoney()  Sets the current record's "vm_money" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSmsValue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sms_value');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('code', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('vm_money', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}