<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TransType', 'doctrine');

/**
 * BaseTransType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $type
 * @property string $code
 * 
 * @method integer   getId()   Returns the current record's "id" value
 * @method string    getType() Returns the current record's "type" value
 * @method string    getCode() Returns the current record's "code" value
 * @method TransType setId()   Sets the current record's "id" value
 * @method TransType setType() Sets the current record's "type" value
 * @method TransType setCode() Sets the current record's "code" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTransType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trans_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('type', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 40,
             ));
        $this->hasColumn('code', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 40,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}