<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CardsValue', 'doctrine');

/**
 * BaseCardsValue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $rm_money
 * @property integer $vm_money
 * @property string $description
 * 
 * @method integer    getId()          Returns the current record's "id" value
 * @method integer    getRmMoney()     Returns the current record's "rm_money" value
 * @method integer    getVmMoney()     Returns the current record's "vm_money" value
 * @method string     getDescription() Returns the current record's "description" value
 * @method CardsValue setId()          Sets the current record's "id" value
 * @method CardsValue setRmMoney()     Sets the current record's "rm_money" value
 * @method CardsValue setVmMoney()     Sets the current record's "vm_money" value
 * @method CardsValue setDescription() Sets the current record's "description" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCardsValue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cards_value');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('rm_money', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('vm_money', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('description', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}