<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Clanrole', 'doctrine');

/**
 * BaseClanrole
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $approve
 * @property integer $kick
 * @property integer $changebio
 * @property integer $sendall
 * 
 * @method integer  getId()        Returns the current record's "id" value
 * @method string   getName()      Returns the current record's "name" value
 * @method integer  getApprove()   Returns the current record's "approve" value
 * @method integer  getKick()      Returns the current record's "kick" value
 * @method integer  getChangebio() Returns the current record's "changebio" value
 * @method integer  getSendall()   Returns the current record's "sendall" value
 * @method Clanrole setId()        Sets the current record's "id" value
 * @method Clanrole setName()      Sets the current record's "name" value
 * @method Clanrole setApprove()   Sets the current record's "approve" value
 * @method Clanrole setKick()      Sets the current record's "kick" value
 * @method Clanrole setChangebio() Sets the current record's "changebio" value
 * @method Clanrole setSendall()   Sets the current record's "sendall" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClanrole extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('clanrole');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('approve', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('kick', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('changebio', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('sendall', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}