<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserBanChat', 'doctrine');

/**
 * BaseUserBanChat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $userid
 * @property timestamp $datecreated
 * @property string $detail
 * 
 * @method integer     getId()          Returns the current record's "id" value
 * @method integer     getUserid()      Returns the current record's "userid" value
 * @method timestamp   getDatecreated() Returns the current record's "datecreated" value
 * @method string      getDetail()      Returns the current record's "detail" value
 * @method UserBanChat setId()          Sets the current record's "id" value
 * @method UserBanChat setUserid()      Sets the current record's "userid" value
 * @method UserBanChat setDatecreated() Sets the current record's "datecreated" value
 * @method UserBanChat setDetail()      Sets the current record's "detail" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserBanChat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_ban_chat');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('userid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('datecreated', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('detail', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}