<?php

/**
 * ActiveEmailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActiveEmailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActiveEmailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActiveEmail');
    }
}