<?php

/**
 * AdminPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdminPermissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdminPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdminPermission');
    }
}