<?php

/**
 * AdminRoleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdminRoleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdminRoleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdminRole');
    }
}