<?php

/**
 * AGameTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AGameTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AGameTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AGame');
    }
}