<?php

/**
 * APaycardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class APaycardTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object APaycardTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('APaycard');
    }
}