<?php

/**
 * ASmstxTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ASmstxTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ASmstxTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ASmstx');
    }
}