<?php

/**
 * AvatarCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AvatarCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AvatarCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AvatarCategory');
    }
}