<?php

/**
 * CardLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CardLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CardLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CardLog');
    }
}