<?php

/**
 * CardsValueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CardsValueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CardsValueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CardsValue');
    }
}