<?php

/**
 * ChargeCardsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChargeCardsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChargeCardsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChargeCards');
    }
}