<?php

/**
 * ClanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Clan');
    }

    public static function getListTopClan()
    {
        return ClanTable::getInstance()->createQuery('a')
            ->select('a.*')
            ->orderBy('a.level desc')
            ->limit(10)
            ->fetchArray();
    }

    public static function getListClan(){
        $q = ClanTable::getInstance()->createQuery('a')
            ->select('a.*')
            ->orderBy('a.level desc');
        return $q->fetchArray();
    }

    public static function getListClanPagination($limit, $offset)
    {

        $q = ClanTable::getInstance()->createQuery('a')
            ->select('a.clanMoney, a.name, a.level')
            ->orderBy('a.level desc');
        $q->offset($offset);
        $q->limit($limit);
        return $q->fetchArray();
    }

}