<?php

/**
 * ClanwallTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClanwallTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClanwallTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Clanwall');
    }
}