<?php

/**
 * ClanmemberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClanmemberTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClanmemberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Clanmember');
    }
}