<?php

/**
 * ClanroleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClanroleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClanroleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Clanrole');
    }
}