<?php

/**
 * DeviceInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeviceInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeviceInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DeviceInfo');
    }
}