<?php

/**
 * EmoticonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmoticonTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmoticonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Emoticon');
    }
}