<?php

/**
 * GameflashTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GameflashTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GameflashTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Gameflash');
    }

    public static function getListGame($slug){
        $q= GameflashTable::getInstance()->createQuery('a')
            ->leftjoin("a.GameflashType t")
            ->select('a.*');
        if($slug)
            $q->where("t.slug =?", $slug);
            return $q->fetchArray();
    }

    public static function checkSlug($slug, $id)
    {
        $query = GameflashTable::getInstance()->createQuery('a')
            ->select('a.slug')
            ->where('a.slug=?', $slug)
            ->andWhere('a.id<>?', $id);
        return $query;
    }
    public static function getGameBySlug($slug)
    {
        return GameflashTable::getInstance()->createQuery('a')
            ->select('a.*')
            ->where('a.slug=?', $slug)
            ->fetchOne();
    }
}