<?php

/**
 * GameHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GameHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GameHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GameHistory');
    }

    public function getListHistoryById($user_id)
    {
        return GameHistoryTable::getInstance()->createQuery('a')
            ->select('a.user_id, a.cash, a.time')
            ->where('a.user_id=?', $user_id)
            ->orderBy('a.time desc')
            ->limit(10)
            ->fetchArray();
    }
}