<?php

/**
 * GameflashTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GameflashTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GameflashTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GameflashType');
    }
    public static function checkSlug($slug, $id)
    {
        $query = GameflashTable::getInstance()->createQuery('a')
            ->select('a.slug')
            ->where('a.slug=?', $slug)
            ->andWhere('a.id<>?', $id);
        return $query;
    }
}