<?php

/**
 * GClientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GClientTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GClientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GClient');
    }
}