<?php

/**
 * MessagetypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MessagetypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MessagetypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Messagetype');
    }
}