<?php

/**
 * OnlineLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OnlineLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OnlineLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OnlineLog');
    }
}