<?php

/**
 * OpenidTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OpenidTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OpenidTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Openid');
    }
}