<?php

/**
 * OptionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OptionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OptionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Options');
    }
}