<?php

/**
 * SmsValueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SmsValueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SmsValueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SmsValue');
    }
}