<?php

/**
 * TransTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TransTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TransTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TransType');
    }
}