<?php

/**
 * UserTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User');
    }

    public function getUserByUsername($username)
    {
        return UserTable::getInstance()->createQuery('a')
            ->select('a.*')
            ->where('a.username=?', $username)
            ->fetchOne();
    }

    public function getUserByUid($username)
    {
        return UserTable::getInstance()->createQuery('a')
            ->andWhere('a.username=?', $username)
            ->fetchOne();
    }
    public static function findById($id)
    {
        return UserTable::getInstance()->createQuery('a')
            ->where('id= ?', $id)
            ->fetchOne();
    }

    /**
     * 03/12/2014 - doanpv_os
     * @param $email
     * @param $username
     * @return bool: kiểm tra sự tồn tại của email, true = ko tồn tại, false = tồn tại
     */
    public static function checkEmailExisted($email, $username = null)
    {
        $pub = UserTable::getInstance()->createQuery('a')
            ->where('email= ?', $email);
        if($username){
            $pub->andwhere('username != ?', $username);
        }
        if($pub->fetchOne()){
            return true;
        }else{
            return false;
        }
    }
}