<?php

/**
 * UserBanChatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserBanChatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserBanChatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserBanChat');
    }
}