<?php

/**
 * UserTempTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTempTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserTempTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserTemp');
    }
}