<?php

/**
 * ViewUserInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ViewUserInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ViewUserInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ViewUserInfo');
    }
}