<?php

/**
 * VtChargAmountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VtChargAmountTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VtChargAmountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VtChargAmount');
    }
}