<?php

/**
 * VtDaiLyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VtDaiLyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VtDaiLyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VtDaiLy');
    }
}