<?php

/**
 * VtpAdvertiseImageTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VtpAdvertiseImageTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object VtpAdvertiseImageTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('VtpAdvertiseImage');
    }

    public static function getImageByAdvertiseId($advertiseId) {
        $q = VtpAdvertiseImageTable::getInstance()->createQuery()
            ->select('file_path, advertise_id, is_active, created_by, created_at')
            ->where('advertise_id=?', $advertiseId);
//            ->andWhere('lang=?',sfContext::getInstance()->getUser()->getCulture());
        return $q;
    }

    public static function getImageByAdvertiseIdOrderByPriority($advertiseId) {
        $q = VtpAdvertiseImageTable::getInstance()->createQuery()
            ->select('file_path, advertise_id, is_active, created_by, created_at')
            ->where('advertise_id=?', $advertiseId)
            ->andWhere('is_active=?',  VtCommonEnum::NUMBER_ONE)
            ->orderBy('priority asc');
        //            ->andWhere('lang=?',sfContext::getInstance()->getUser()->getCulture());
        return $q;
    }

    public static function getCountImage($advertiseId) {
        $q = VtpAdvertiseImageTable::getInstance()->createQuery()
            ->select('file_path, advertise_id, is_active, created_by, created_at')
            ->where('advertise_id=?', $advertiseId);
//            ->andWhere('lang=?',sfContext::getInstance()->getUser()->getCulture());
        return $q->count();
    }

    public static function deleteImageByAdvertise($advertiseId) {
        return VtpAdvertiseImageTable::getInstance()->createQuery()
            ->delete()
            ->whereIn('advertise_id', $advertiseId)->execute();
    }

}