<?php

/**
 * VtpAdvertiseLocationTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VtpAdvertiseLocationTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object VtpAdvertiseLocationTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('VtpAdvertiseLocation');
    }

    public function getAllForSelectionBoxQuery() {
        return $this->createQuery('a')
            ->select('a.id, a.name')
            ->where('a.portal_id=?',sfContext::getInstance()->getUser()->getAttribute('portal',0))
            ->orderBy('a.priority asc, a.name asc');
    }

    public static function getLocationByPortal($portalId) {
        return VtpAdvertiseLocationTable::getInstance()->createQuery()
            ->select('id, name')
            ->andWhere('portal_id=?',$portalId)
            ->orderBy('priority asc, name asc')->fetchArray();
    }

    public function getAllForSelectionBox() {
        return $this->getAllForSelectionBoxQuery(sfContext::getInstance()->getUser()->getAttribute('portal',0))
            ->execute();
    }

    public static function getAdvertiseLocationByID($advertisId) {
        return VtpAdvertiseLocationTable::getInstance()->createQuery()
            ->select('id, name')
            ->orderBy('priority asc')
            ->where('advertise_id = ?', $advertisId)
            ->execute();
    }

    //Cập nhật banner quảng cáo vào vị trí quảng cáo
    public static function updateLocationAdvertise($advertisId, $arrLocaltionId) {

//        VtpAdvertiseLocationTable::getInstance()->createQuery()
//                ->update()
//                ->set('advertise_id', 'NULL')
//                ->where('advertise_id', $advertisId)
//                ->execute();

//        update vtp_advertise_location set advertise_id = null where advertise_id = ?

        $query2 = VtpAdvertiseLocationTable::getInstance()->createQuery()
            ->update()
            ->set('advertise_id', $advertisId)
            ->whereIn('id', $arrLocaltionId);

        return $query2->execute();
    }

}