<?php

/**
 * VtpHtmlTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VtpHtmlTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VtpHtmlTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VtpHtml');
    }

    public static function checkSlug($slug,$id)
    {
        $query=  VtpHtmlTable::getInstance()->createQuery()
            ->select('slug')
            ->where('slug=?',$slug)
            ->andWhere('id<>?',$id);
        return $query;
    }

    public static  function getAllHtml($lang,$portalId)
    {
        $query=  VtpHtmlTable::getInstance()->createQuery()
            ->select('slug, prefix_path')
            ->where('is_active=?',VtCommonEnum::NUMBER_ONE)
            ->andWhere('portal_id=?',$portalId)
            ->andWhere('lang=?',$lang);
        return $query->execute();
    }

    public static function getHtmlByHtml($slug,$portalId){
        $query=  VtpHtmlTable::getInstance()->createQuery()
            ->where('is_active=?',VtCommonEnum::NUMBER_ONE)
            ->andWhere('slug=?',$slug)
            ->andWhere('portal_id=?',$portalId)
            ->andWhere('lang=?',sfContext::getInstance()->getUser()->getCulture());
        return $query->fetchOne();
    }
}