<?php

/**
 * VtSerialCodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VtSerialCodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VtSerialCodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VtSerialCode');
    }

    public static function checkSerialInput($seria, $cardnumber, $type)
    {
        VtSerialCodeTable::getInstance()->createQuery('a')
            ->leftJoin('a.VtChargAmount m')
            ->select('m.charg_amount as chard_amount, a.*')
            ->where('a.serial = ?', $seria)
            ->andWhere('a.cardnumber =?', $cardnumber)
            ->andWhere('a.type =?', $type)
            ->andWhere('a.is_status =?', VtCommonEnum::NUMBER_ZERO)
            ->fetchOne();
    }
    
    public static function getMoneyCheck(){
        return VtSerialCodeTable::getInstance()->createQuery('a')
                  ->select('a.is_status, sum(m.charg_amount) as sum_money')
                  ->leftJoin('a.VtChargAmount m')
                  ->groupBy('a.is_status')
                  ->fetchArray();
    }
}