all:
  slave:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost:3306;dbname=gonline'
      username: root
      password: ''
      attributes: { default_table_charset: utf8, default_table_collate: utf8_general_ci }
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost:3306;dbname=gonline'
#      dsn: 'mysql:host=103.28.37.24;dbname=gonline'
#      username: vtp_v2
      username: root
      password: ''
 #     password: mysql!mi14@
      attributes: { default_table_charset: utf8, default_table_collate: utf8_general_ci }