generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           Announcement
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          announcement
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
       object_actions:
          _edit: {label: Chi tiết}
          _delete: ~
      filter:
        display: [subject]
      form:    ~
      edit:    ~
      new:     ~
